openapi: 3.0.1
info:
  title: DH Voice app
  description: REST API of DH Voice test app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: DH Voice test environment
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: >-
        May contain hints how to solve the error or indicate what went wrong at
        the server. Must not outline any information about the internal
        structure of the server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ClientError:
      description: >-
        May contain hints how to solve the error or indicate what was wrong in
        the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    ONKZ:
      type: string
      minLength: 2
      maxLength: 5
      pattern: '[2-9]\d'
    Number:
      type: string
      minLength: 3
      maxLength: 9
      pattern: '[1-9]\d'
tags:
  - name: Numbers
paths:
  /numbers/{onkz}/{number}:
    get:
      tags:
        - Numbers
      summary: Return status of the number provided
      operationId: getNumberStatus
      parameters: 
        - name: onkz
          in: path
          description: ONKZ part
          required: true
          example: 201
          schema:
            $ref: '#/components/schemas/ONKZ'
        - name: number
          in: path
          description: the Number part
          required: true
          example: 11111111
          schema:
            $ref: '#/components/schemas/Number'
      responses:
        '200':
          description: List of meta data of available Self-Descriptions.
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/ClientError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
